//import type { Metadata } from "next";
import { Roboto, M_PLUS_1p } from 'next/font/google';
import "src/globals.css";
import { Toaster } from "react-hot-toast";
import { Providers }from "./providers";

export const roboto = Roboto({
  weight: ['300','400','500'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
  preload: false
});

export const m_plus_1p = M_PLUS_1p({
  weight: ['400','500','700'],
  subsets: ['latin'],
  variable: '--font-m-plus-1p',
  display: 'swap',
  preload: false
})
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${m_plus_1p.variable} ${roboto.variable}`}>
        <Providers>
          
          {children}
          <Toaster position="top-center" reverseOrder={false} />
        </Providers>
      </body>
    </html>
  );
}
